version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.3
  continuation: circleci/continuation@0.3.1
parameters:
  scheduled:
    type: boolean
    default: false
jobs:
  filter-paths:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision: main
          mapping: |
            scripts/.*     skip-run  true
          output-path: /tmp/pipeline-parameters.json
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          parameters: /tmp/pipeline-parameters.json
workflows:
  choose-config:
    jobs:
      - filter-paths
